version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /W2/internal/example1/svelte
      - /W2/internal/example2/svelte
    target-branch: security/fast-uri-pnpm
    schedule:
      interval: daily
      time: "10:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    allow:
      - dependency-name: fast-uri
