version: "3.3"

services:
  meilisearch-0.25.0:
    image: "getmeili/meilisearch:v0.25.0"
    ports:
      - "7720:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_NO_SENTRY=true
      # - MEILI_MASTER_KEY=test_api_key