package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"example2/domain"
)

var allCommands = []string{
	domain.GuestAutoLoginAction,
	domain.GuestDebugAction,
	domain.GuestExternalAuthAction,
	domain.GuestForgotPasswordAction,
	domain.GuestLoginAction,
	domain.GuestOauthCallbackAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.SuperAdminDashboardAction,
	domain.SuperAdminUserManagementAction,
	domain.UserAutoLoginLinkAction,
	domain.UserChangePasswordAction,
	domain.UserLogoutAction,
	domain.UserProfileAction,
	domain.UserSessionKillAction,
	domain.UserSessionsActiveAction,
	domain.UserUpdateProfileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
